
# Efinity Option Register
# Version: 2025.2.288.3.8
# Date: 2026-04-22 23:52

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

enable_remote_update=off
remote_update_retries=3
seu_wait_interval=0xffffff
enable_seu_crc_check=off
seu_mode=automatic
